language: rust
dist: trusty
sudo: required

cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

rust:
  # stable is unsupport 2018 edition
  # - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview
  - cargo install cargo-travis || echo "cargo-travis already installed"

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
  - cargo fmt
  - cargo build

after_success:
  - cargo coveralls
  - cargo doc-upload
