language: rust
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

rust:
  - nightly

services:
  - postgresql

before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview
  - cargo install diesel_cli || echo 'diesel_cli already installed'
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - psql -c 'create database peco_test;' -U postgres
  - echo DATABASE_URL=postgres://postgres@localhost/peco_test> .env
  - cp config/database.yml.travis config/database.yml

script:
  - cargo fmt
  - cargo clippy --all-targets --all-features -- -D warnings
  - diesel migration run
  - cargo build
  - cargo test

after_success:
  - cargo coveralls
  - cargo doc-upload
